-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: May 16, 2025 at 08:22 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `db_lms`
--

-- --------------------------------------------------------

--
-- Table structure for table `borrowers`
--

CREATE TABLE `borrowers` (
  `borrower_id` int(11) NOT NULL,
  `firstname` varchar(100) NOT NULL,
  `middlename` varchar(100) NOT NULL,
  `lastname` varchar(100) NOT NULL,
  `contact_no` varchar(15) NOT NULL,
  `address` text NOT NULL,
  `email` varchar(30) NOT NULL,
  `tax_id` varchar(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- --------------------------------------------------------

--
-- Table structure for table `loan`
--

CREATE TABLE `loan` (
  `loan_id` int(11) NOT NULL,
  `ref_no` varchar(50) NOT NULL,
  `ltype_id` int(30) NOT NULL,
  `borrower_id` int(30) NOT NULL,
  `purpose` text NOT NULL,
  `amount` double NOT NULL,
  `lplan_id` int(30) NOT NULL,
  `status` tinyint(1) NOT NULL COMMENT '0=request, 1=confirmed, 2=released, 3=completed, 4=denied',
  `date_released` datetime NOT NULL,
  `date_created` datetime NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- --------------------------------------------------------

--
-- Table structure for table `loan_applications`
--

CREATE TABLE `loan_applications` (
  `application_id` int(11) NOT NULL,
  `user_id` int(11) NOT NULL,
  `loan_plan_id` int(11) NOT NULL,
  `requested_amount` decimal(15,2) NOT NULL,
  `loan_purpose` text DEFAULT NULL,
  `application_date` datetime DEFAULT current_timestamp(),
  `status` varchar(50) NOT NULL DEFAULT 'Pending',
  `last_updated_at` datetime DEFAULT current_timestamp() ON UPDATE current_timestamp(),
  `applicant_first_name` varchar(100) NOT NULL,
  `applicant_last_name` varchar(100) NOT NULL,
  `applicant_email` varchar(255) NOT NULL,
  `applicant_phone_number` varchar(20) DEFAULT NULL,
  `applicant_date_of_birth` date DEFAULT NULL,
  `applicant_address_line1` varchar(255) DEFAULT NULL,
  `applicant_address_line2` varchar(255) DEFAULT NULL,
  `applicant_city` varchar(100) DEFAULT NULL,
  `applicant_province_state` varchar(100) DEFAULT NULL,
  `applicant_postal_code` varchar(20) DEFAULT NULL,
  `applicant_country` varchar(100) DEFAULT NULL,
  `employment_status` varchar(50) DEFAULT NULL,
  `employer_name` varchar(255) DEFAULT NULL,
  `job_title` varchar(100) DEFAULT NULL,
  `years_in_employment` int(11) DEFAULT NULL,
  `monthly_income` decimal(15,2) DEFAULT NULL,
  `other_income_sources` text DEFAULT NULL,
  `credit_score` int(11) DEFAULT NULL,
  `reviewed_by_user_id` int(11) DEFAULT NULL,
  `review_date` datetime DEFAULT NULL,
  `reviewer_notes` text DEFAULT NULL,
  `approved_amount` decimal(15,2) DEFAULT NULL,
  `approved_interest_rate` decimal(5,2) DEFAULT NULL,
  `approved_term_months` int(11) DEFAULT NULL,
  `approved_monthly_installment` decimal(15,2) DEFAULT NULL,
  `disbursement_date` date DEFAULT NULL,
  `first_payment_date` date DEFAULT NULL,
  `loan_agreement_document_id` varchar(255) DEFAULT NULL,
  `consent_to_credit_check` tinyint(1) DEFAULT 0,
  `declaration_accuracy` tinyint(1) DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `loan_application_documents`
--

CREATE TABLE `loan_application_documents` (
  `document_id` int(11) NOT NULL,
  `application_id` int(11) NOT NULL,
  `document_type` varchar(100) DEFAULT NULL,
  `file_name` varchar(255) NOT NULL,
  `file_path` varchar(512) NOT NULL,
  `mime_type` varchar(100) DEFAULT NULL,
  `file_size_kb` int(11) DEFAULT NULL,
  `uploaded_at` datetime DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `loan_plans`
--

CREATE TABLE `loan_plans` (
  `id` varchar(50) NOT NULL COMMENT 'Unique identifier for the loan plan (e.g., generated by uniqid)',
  `title` varchar(255) NOT NULL COMMENT 'Title of the loan plan (e.g., Personal Loan)',
  `icon_svg` text DEFAULT NULL COMMENT 'Full SVG code for the plan''s icon',
  `description` text DEFAULT NULL COMMENT 'Detailed description of the loan plan',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Timestamp of when the plan was created',
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Timestamp of when the plan was last updated'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `loan_schedule`
--

CREATE TABLE `loan_schedule` (
  `loan_sched_id` int(50) NOT NULL,
  `loan_id` int(11) NOT NULL,
  `due_date` date NOT NULL,
  `amount_due` float NOT NULL,
  `status` enum('unsettled','settled') NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

-- --------------------------------------------------------

--
-- Table structure for table `loan_terms`
--

CREATE TABLE `loan_terms` (
  `id` int(11) NOT NULL COMMENT 'Auto-incrementing unique ID for the term',
  `loan_plan_id` varchar(50) NOT NULL COMMENT 'Foreign key referencing the id in loan_plans table',
  `term_key` varchar(100) NOT NULL COMMENT 'Identifier for the term (e.g., 6_months, 12_months_promo)',
  `interest_rate_details` varchar(255) DEFAULT NULL COMMENT 'Descriptive text for the interest rate (e.g., 1.5% / month)',
  `penalty_details` varchar(255) DEFAULT NULL COMMENT 'Descriptive text for the late payment penalty (e.g., 5% of overdue amount + P500)',
  `is_promotional` tinyint(1) DEFAULT 0 COMMENT 'Flag to indicate if this term is part of a promotion (0 for false, 1 for true)',
  `created_at` timestamp NOT NULL DEFAULT current_timestamp() COMMENT 'Timestamp of when the term was created',
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp() COMMENT 'Timestamp of when the term was last updated'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `loan_type`
--

CREATE TABLE `loan_type` (
  `ltype_id` int(11) NOT NULL,
  `ltype_name` varchar(100) NOT NULL,
  `ltype_description` text DEFAULT NULL,
  `is_active` tinyint(1) DEFAULT 1,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `payment`
--

CREATE TABLE `payment` (
  `payment_id` int(11) NOT NULL,
  `loan_id` int(11) NOT NULL,
  `payee` varchar(200) DEFAULT NULL,
  `payment_method` varchar(50) NOT NULL,
  `pay_amount` decimal(12,2) NOT NULL,
  `penalty` decimal(10,2) DEFAULT 0.00,
  `overdue` tinyint(1) DEFAULT 0 COMMENT '1=Payment was for an overdue amount, 0=Not overdue related',
  `proof_of_payment` varchar(255) DEFAULT NULL,
  `reference_no` varchar(100) DEFAULT NULL,
  `other_details` text DEFAULT NULL,
  `payment_date` timestamp NOT NULL DEFAULT current_timestamp(),
  `status` enum('Pending','Verified','Failed') DEFAULT 'Pending' COMMENT 'Admin verification status',
  `verified_by` int(11) DEFAULT NULL COMMENT 'Admin user_id who verified',
  `date_verified` datetime DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `penalty`
--

CREATE TABLE `penalty` (
  `penalty_id` int(11) NOT NULL,
  `loan_id` int(11) NOT NULL,
  `amount` decimal(10,2) NOT NULL,
  `reason` varchar(255) DEFAULT 'Late Payment',
  `penalty_date` date NOT NULL,
  `status` enum('Unpaid','Paid') DEFAULT 'Unpaid',
  `payment_id_cleared` int(11) DEFAULT NULL COMMENT 'Payment ID that cleared this penalty',
  `date_created` timestamp NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `profile`
--

CREATE TABLE `profile` (
  `user_id` int(11) NOT NULL,
  `firstname` varchar(75) NOT NULL,
  `lastname` varchar(75) NOT NULL,
  `username` varchar(50) NOT NULL,
  `email` varchar(100) NOT NULL,
  `phone` varchar(25) DEFAULT NULL,
  `profile_pic` varchar(255) DEFAULT 'default.png',
  `bio` text DEFAULT NULL,
  `password` varchar(255) NOT NULL,
  `created_at` timestamp NOT NULL DEFAULT current_timestamp(),
  `updated_at` timestamp NOT NULL DEFAULT current_timestamp() ON UPDATE current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- --------------------------------------------------------

--
-- Table structure for table `user`
--

CREATE TABLE `user` (
  `user_id` int(11) NOT NULL,
  `profile_pic` longblob NOT NULL,
  `bio` text DEFAULT NULL,
  `username` varchar(30) NOT NULL,
  `password` text NOT NULL,
  `role_id` int(11) NOT NULL,
  `firstname` text NOT NULL,
  `lastname` text NOT NULL,
  `phone` varchar(15) NOT NULL,
  `email` varchar(255) NOT NULL,
  `status` text NOT NULL,
  `verification_code` varchar(6) DEFAULT NULL,
  `otp_expiry` datetime DEFAULT NULL,
  `reset_token` text NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

--
-- Dumping data for table `user`
--

INSERT INTO `user` (`user_id`, `profile_pic`, `bio`, `username`, `password`, `role_id`, `firstname`, `lastname`, `phone`, `email`, `status`, `verification_code`, `otp_expiry`, `reset_token`) VALUES
(2, '', NULL, 'admin', '$2y$10$mMK7i6..yFXzLtWJwX5i/ebqY9KORJkvxADQg80Q9gXL1ymy2qVSW', 1, 'Administrator', '', '', '', '', NULL, NULL, ''),
(16, 0x70726f66696c655f31365f363831663865313531653337362e6a7067, NULL, 'Myra', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'Myra', 'Soliman', '09707738218', 'solimanmyra333@gmail.com', 'active', NULL, NULL, '5f4ba7dc249f3c0a5e8281ef430e6da7'),
(17, '', NULL, 'my', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'myra', 'soliman', '', 'solimanmyra333@gmail.com', 'active', NULL, NULL, 'bbdbc39138bba27b8656381d691585dd'),
(18, '', NULL, 'my', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'myra', 'soliman', '', 'solimanmyra333@gmail.com', 'active', NULL, NULL, '25b3c59cb5912671b1c03212730b0724'),
(19, '', NULL, 'my', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'myra', 'soliman', '', 'solimanmyra333@gmail.com', 'active', NULL, NULL, '72c374d17f032db5635a5e464b1dec49'),
(20, '', NULL, 'my', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'myra', 'soliman', '', 'solimanmyra333@gmail.com', 'active', NULL, NULL, '4e5894bba13d248b78190604f69cb9e7'),
(21, '', NULL, 'my', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'myra', 'soliman', '', 'solimanmyra333@gmail.com', 'active', NULL, NULL, 'ad535ece5490b5da5f65c0a23c1dd177'),
(22, '', NULL, 'my', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'myra', 'soliman', '', 'solimanmyra333@gmail.com', 'active', NULL, NULL, 'b2f6c315ae0e2a9be736016724cac994'),
(23, '', NULL, 'myra', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'myra', 'soliman', '', 'solimanmyra333@gmail.com', 'active', NULL, NULL, '93657b043e26bc60be038f350d04c25e'),
(24, 0x70726f66696c655f32345f363832303164656131313839342e6a7067, NULL, 'ff', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'f', 'f', '09707738218', 'solimanmyra333@gmail.com', 'active', NULL, NULL, 'e01f04bf37ff9679a97a7e213b7ffc45'),
(25, '', NULL, 'Myra', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'ncksj', 'nckl', '', 'solimanmyra333@gmail.com', 'active', NULL, NULL, 'cd3da03b9ef43c9284f184239ce7c1b4'),
(26, 0x70726f66696c655f32365f36383233353433313832613337322e38363635363331352e6a7067, NULL, 'd', '$2y$10$mMK7i6..yFXzLtWJwX5i/ebqY9KORJkvxADQg80Q9gXL1ymy2qVSW', 2, 'Myra', 'Soliman', '09707738218', 'solimanmyra333@gmail.com', 'active', NULL, NULL, 'ea14917bd3a46ad730f6ec48f8425dd1'),
(27, '', NULL, 'myra', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'myra', 'soliman', '', 'solimanmyra333@gmail.com', 'pending', NULL, '2025-05-12 07:01:39', '99bec8181b5fcc7e2f1c76c42fced4ba'),
(28, '', NULL, 'myra', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'myra', 'soliman', '', 'solimanmyra333@gmail.com', 'pending', NULL, '2025-05-12 07:06:53', '88f968ce1fa134bf675bdeb1d5c5a751'),
(29, '', NULL, 'myra', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'myra', 'soliman', '', 'solimanmyra333@gmail.com', 'pending', NULL, '2025-05-12 07:12:45', '21b5e9378594924003fdf40c032d7a6b'),
(30, '', NULL, 'myra', '$2y$10$LL7SsZ5pIxjGsp8lYRIxSeTClMtNb0KLCUKEsKcjTZcSlzibOtS7G', 2, 'smflkn', 'msfklsq', '', 'solimanmyra333@gmail', 'pending', '307361', '2025-05-12 15:34:25', '8220c7a8098df60eb02d31d0a39530a2'),
(31, '', NULL, 'myra', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'smflkn', 'msfklsq', '', 'solimanmyra333@gmail.com', 'pending', NULL, '2025-05-12 15:34:36', 'adc68453d02773510e5a544ce2bbae1e'),
(32, '', NULL, 'k', '$2y$10$BJD5jJ/tHz4S2InxdRVyF.7vWNfYmb1aAZhE0jQjTVsgR2wt2XoNa', 2, 'kd', 'hgjbj', '', 'ghhsdgag@gmail.com', 'pending', '686914', '2025-05-14 04:33:36', '5b1d29ee8fa9f5c2fe2e04b5431eab06'),
(33, '', NULL, 'jen', '$2y$10$evamSVBL/96a397tQEkeceFKPwxacHe13KP5rsaQPqIEnqCm4vzhG', 2, 'jen', 'hernandez', '', 'camilledaganto@gmail.com', 'pending', '182120', '2025-05-14 06:39:24', '7d2388936968f325848071e3314da3df'),
(34, '', NULL, 'jen', '$2y$10$Beykh4YgsuKJ3NoucR.FOevLfAAF2EMEuBJCoAQuv87lCGorH7zPS', 2, 'jen', 'hernandez', '', 'camilledaganto@gmail.com', 'pending', '653459', '2025-05-14 06:40:35', 'ab451da2865adfe3a5359006107251da'),
(35, '', NULL, 'jen', '$2y$10$aBX4lFuI8x5cpog4jEKQNeuLLYa3yiwRIqfVejsv3YHhD1fNGNG.u', 2, 'jennevie', 'hernandez', '', 'camilledaganto@gmail.com', 'pending', '409855', '2025-05-14 06:41:06', '21d049571f8b12aa92aea7b1fd4b9270'),
(36, '', NULL, 'jen', '$2y$10$dc/NBmB9p.kwn2MMFmk13e0p.yS2CYDHGKUHMmc8MoF3DzuSxB93q', 2, 'jennevie', 'hernandez', '', 'camilledaganto@gmail.com', 'pending', '324912', '2025-05-14 06:42:23', 'c00646d94a59beb2cec0ffd27377b020'),
(37, '', NULL, 'gioqfhiq', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'kngdxio', 'djsk', '', 'solimanmyra333@gmail.com', 'pending', NULL, '2025-05-14 06:43:36', '6fdd2e9297c9d7fb75fea8b74df4da14'),
(38, '', NULL, 'sf', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'fs', 'fdsg', '', 'solimanmyra333@gmail.com', 'pending', NULL, '2025-05-14 06:45:01', '2527f9de524d5acc8580ffa0ca8eebb2'),
(39, '', NULL, 'sf', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'faw', 'dsfs', '', 'solimanmyra333@gmail.com', 'pending', NULL, '2025-05-14 06:47:38', 'f1e10245cfc0e19d0ddf42b202349435'),
(40, '', NULL, 'sf', '$2y$10$qqxlGoPWzMBpR3hpnCHqn.I9WiNyM8vnjR2eRPjBf6ggxYAiSAbuK', 2, 'faw', 'dsfs', '', 'solimanmyra333@gmail.com', 'pending', NULL, '2025-05-14 06:49:11', '382b74066426d0e79b55148e07813f2d'),
(41, '', NULL, 'm', '$2y$10$24LgI7TYl5qKzwfM1/GBHeH7uQ8WIOoiFpJtDe1T0yRaBHSBp.vZG', 2, 'Myra', 'soliman', '', 'solimanmyra333@gmail.com', 'pending', '359382', '2025-05-16 04:59:01', 'e5d8c7b517106af8f370f6894065f3a2');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `borrowers`
--
ALTER TABLE `borrowers`
  ADD PRIMARY KEY (`borrower_id`);

--
-- Indexes for table `loan`
--
ALTER TABLE `loan`
  ADD PRIMARY KEY (`loan_id`);

--
-- Indexes for table `loan_applications`
--
ALTER TABLE `loan_applications`
  ADD PRIMARY KEY (`application_id`),
  ADD KEY `idx_user_id` (`user_id`),
  ADD KEY `idx_loan_plan_id` (`loan_plan_id`),
  ADD KEY `idx_status` (`status`),
  ADD KEY `idx_application_date` (`application_date`);

--
-- Indexes for table `loan_application_documents`
--
ALTER TABLE `loan_application_documents`
  ADD PRIMARY KEY (`document_id`),
  ADD KEY `fk_application_document` (`application_id`);

--
-- Indexes for table `loan_plans`
--
ALTER TABLE `loan_plans`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `loan_schedule`
--
ALTER TABLE `loan_schedule`
  ADD PRIMARY KEY (`loan_sched_id`);

--
-- Indexes for table `loan_terms`
--
ALTER TABLE `loan_terms`
  ADD PRIMARY KEY (`id`),
  ADD UNIQUE KEY `unique_plan_term_key` (`loan_plan_id`,`term_key`) COMMENT 'Ensures a loan plan cannot have duplicate term keys';

--
-- Indexes for table `loan_type`
--
ALTER TABLE `loan_type`
  ADD PRIMARY KEY (`ltype_id`),
  ADD UNIQUE KEY `ltype_name` (`ltype_name`);

--
-- Indexes for table `payment`
--
ALTER TABLE `payment`
  ADD PRIMARY KEY (`payment_id`),
  ADD KEY `loan_id` (`loan_id`),
  ADD KEY `verified_by` (`verified_by`);

--
-- Indexes for table `penalty`
--
ALTER TABLE `penalty`
  ADD PRIMARY KEY (`penalty_id`),
  ADD KEY `loan_id` (`loan_id`),
  ADD KEY `payment_id_cleared` (`payment_id_cleared`);

--
-- Indexes for table `profile`
--
ALTER TABLE `profile`
  ADD PRIMARY KEY (`user_id`),
  ADD UNIQUE KEY `username_UNIQUE` (`username`),
  ADD UNIQUE KEY `email_UNIQUE` (`email`);

--
-- Indexes for table `user`
--
ALTER TABLE `user`
  ADD PRIMARY KEY (`user_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `borrowers`
--
ALTER TABLE `borrowers`
  MODIFY `borrower_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `loan`
--
ALTER TABLE `loan`
  MODIFY `loan_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `loan_applications`
--
ALTER TABLE `loan_applications`
  MODIFY `application_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `loan_application_documents`
--
ALTER TABLE `loan_application_documents`
  MODIFY `document_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `loan_schedule`
--
ALTER TABLE `loan_schedule`
  MODIFY `loan_sched_id` int(50) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `loan_terms`
--
ALTER TABLE `loan_terms`
  MODIFY `id` int(11) NOT NULL AUTO_INCREMENT COMMENT 'Auto-incrementing unique ID for the term';

--
-- AUTO_INCREMENT for table `loan_type`
--
ALTER TABLE `loan_type`
  MODIFY `ltype_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `payment`
--
ALTER TABLE `payment`
  MODIFY `payment_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `penalty`
--
ALTER TABLE `penalty`
  MODIFY `penalty_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `profile`
--
ALTER TABLE `profile`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `user`
--
ALTER TABLE `user`
  MODIFY `user_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=42;

--
-- Constraints for dumped tables
--

--
-- Constraints for table `loan_application_documents`
--
ALTER TABLE `loan_application_documents`
  ADD CONSTRAINT `fk_application_document` FOREIGN KEY (`application_id`) REFERENCES `loan_applications` (`application_id`) ON DELETE CASCADE;

--
-- Constraints for table `loan_terms`
--
ALTER TABLE `loan_terms`
  ADD CONSTRAINT `loan_terms_ibfk_1` FOREIGN KEY (`loan_plan_id`) REFERENCES `loan_plans` (`id`) ON DELETE CASCADE ON UPDATE CASCADE;

--
-- Constraints for table `payment`
--
ALTER TABLE `payment`
  ADD CONSTRAINT `payment_ibfk_1` FOREIGN KEY (`loan_id`) REFERENCES `loan` (`loan_id`) ON DELETE CASCADE,
  ADD CONSTRAINT `payment_ibfk_2` FOREIGN KEY (`verified_by`) REFERENCES `users` (`user_id`) ON DELETE SET NULL;

--
-- Constraints for table `penalty`
--
ALTER TABLE `penalty`
  ADD CONSTRAINT `penalty_ibfk_1` FOREIGN KEY (`loan_id`) REFERENCES `loan` (`loan_id`) ON DELETE CASCADE,
  ADD CONSTRAINT `penalty_ibfk_2` FOREIGN KEY (`payment_id_cleared`) REFERENCES `payment` (`payment_id`) ON DELETE SET NULL;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
